import { defineConfig, presetUno, presetIcons } from "unocss";

export default defineConfig({
  presets: [presetUno(), presetIcons()],
  shortcuts: {
    "kiosk-screen": "min-h-screen flex flex-col items-center justify-center bg-gray-50 p-4",
    "kiosk-panel": "bg-white rounded-3xl shadow-xl w-full max-w-2xl p-8 flex flex-col gap-6",
    "kiosk-panel-title": "text-3xl font-bold text-center text-gray-800",
    "kiosk-panel-subtitle": "text-lg text-center text-gray-500",
    "kiosk-input": "w-full px-4 py-3 border-2 border-gray-200 rounded-xl text-xl focus:outline-none focus:ring-4 focus:ring-blue-100 focus:border-blue-500",
    "kiosk-label": "block text-base font-semibold text-gray-700 mb-2",
    "kiosk-input-group": "flex flex-col",
    "kiosk-btn": "inline-flex items-center justify-center gap-2 rounded-xl font-bold transition-all disabled:opacity-50 disabled:cursor-not-allowed min-h-16 text-xl",
    "kiosk-btn-primary": "kiosk-btn bg-blue-600 text-white hover:bg-blue-700 px-8 py-4",
    "kiosk-btn-outline": "kiosk-btn bg-white text-gray-700 border-2 border-gray-200 hover:border-gray-400 hover:bg-gray-50 px-6 py-3",
    "kiosk-btn-danger": "kiosk-btn bg-red-600 text-white hover:bg-red-700 px-8 py-4",
    "kiosk-btn-warning": "kiosk-btn text-amber-900 border-2 border-amber-300 hover:bg-amber-50 px-6 py-3",
    "kiosk-error": "p-4 bg-red-100 text-red-800 rounded-xl text-lg font-semibold text-center",
    "kiosk-message": "p-4 bg-blue-50 text-blue-800 rounded-xl text-lg text-center",
    "kiosk-header": "w-full bg-deepnavy text-white px-6 py-3 flex items-center justify-between",
    "kiosk-header-user": "flex flex-col",
    "kiosk-header-logout": "text-sm text-gray-400 hover:text-white transition-colors",
    "kiosk-header-mode-btn": "px-4 py-2 rounded-lg text-sm font-semibold border border-transparent transition-colors",
    "kiosk-header-mode-active": "bg-blue-600 text-white",
    "kiosk-header-mode-refill": "bg-amber-400 text-amber-900",
    "kiosk-refill-banner": "bg-peach text-amber-900 text-center py-3 text-xl font-bold",
    "rx-list": "flex flex-col gap-4 list-none p-0",
    "rx-card": "p-5 bg-gray-50 rounded-2xl border border-gray-100 flex items-center justify-between cursor-pointer hover:bg-blue-50 hover:border-blue-200 transition-colors",
    "rx-card-patient": "text-xl font-bold text-gray-800",
    "rx-card-drugs": "text-base text-gray-500",
    "rx-card-hn": "text-sm text-gray-400 font-mono",
    "rx-detail": "flex flex-col gap-4",
    "rx-detail-section": "bg-gray-50 rounded-xl p-4",
    "rx-detail-heading": "text-sm font-semibold text-gray-500 uppercase tracking-wide",
    "rx-detail-value": "text-xl font-bold text-gray-800 mt-1",
    "rx-detail-items": "flex flex-col gap-2 list-none p-0",
    "rx-detail-item": "flex items-center justify-between py-1",
    "rx-detail-item-name": "text-lg text-gray-700",
    "rx-detail-item-qty": "text-xl font-bold text-blue-700",
    "dispense-status": "flex flex-col items-center gap-4 py-8",
    "dispense-status-icon": "text-6xl",
    "dispense-status-verdict": "text-3xl font-bold text-gray-800",
    "dispense-status-detail": "text-xl text-gray-500 text-center",
    "refill-stock-badge": "text-2xl font-bold",
    "refill-progress": "w-full h-3 bg-gray-200 rounded-full mt-1 overflow-hidden",
    "refill-progress-fill": "h-full rounded-full bg-green-500 transition-all",
    "step-indicator": "text-sm font-semibold text-gray-400 uppercase tracking-wide",
    "spinner": "w-10 h-10 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mx-auto",
    "login-divider": "flex items-center gap-4 text-sm text-gray-400 uppercase",
    "login-divider-line": "flex-1 h-px bg-gray-200",
    "card-scan-area": "flex flex-col items-center gap-3 p-8 border-2 border-dashed border-gray-300 rounded-2xl cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition-colors",
  },
  theme: {
    colors: {
      deepnavy: "#1e1e2e",
      peach: "#fab387",
    },
  },
});
