import { defineConfig, presetUno, presetIcons } from "unocss";

export default defineConfig({
  presets: [presetUno(), presetIcons()],
  shortcuts: {
    "page-header": "flex items-center justify-between mb-6",
    "page-title": "text-2xl font-bold text-deepnavy",
    "search-bar": "mb-4",
    "search-input": "w-full max-w-md px-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500",
    "table-wrap": "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden",
    "table-th": "px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider bg-gray-50",
    "table-td": "px-4 py-3 text-sm text-gray-700 whitespace-nowrap",
    "btn-primary": "inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors",
    "btn-secondary": "inline-flex items-center gap-2 px-4 py-2 bg-gray-100 text-gray-700 text-sm font-semibold rounded-lg hover:bg-gray-200 transition-colors",
    "btn-ghost": "text-sm text-gray-500 hover:text-gray-700 px-2 py-1 rounded hover:bg-gray-100 transition-colors",
    "btn-danger": "inline-flex items-center gap-2 px-4 py-2 bg-red-600 text-white text-sm font-semibold rounded-lg hover:bg-red-700 disabled:opacity-50 transition-colors",
    "badge": "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium",
    "badge-active": "badge bg-green-100 text-green-800",
    "badge-inactive": "badge bg-gray-100 text-gray-500",
    "badge-warning": "badge bg-yellow-100 text-yellow-800",
    "badge-error": "badge bg-red-100 text-red-800",
    "modal-overlay": "fixed inset-0 z-50 flex items-center justify-center bg-black/40",
    "modal": "bg-white rounded-2xl shadow-xl w-full max-w-lg mx-4 p-6 max-h-[90vh] overflow-y-auto",
    "modal-title": "text-lg font-bold text-gray-800 mb-4",
    "form-group": "mb-4",
    "form-label": "block text-sm font-medium text-gray-700 mb-1",
    "form-input": "w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
    "form-select": "w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500",
    "form-row": "grid grid-cols-2 gap-4",
    "form-actions": "flex justify-end gap-3 mt-6",
    "inline-actions": "flex items-center gap-1",
    "login-page": "min-h-screen flex items-center justify-center bg-gray-50",
    "login-panel": "bg-white rounded-2xl shadow-lg p-8 w-full max-w-sm",
    "login-title": "text-xl font-bold text-center mb-2",
    "login-error": "text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg p-3 mb-4",
    "login-field": "mb-4",
    "login-label": "block text-sm font-medium text-gray-700 mb-1",
    "empty-state": "text-center py-12 text-gray-400 text-sm",
  },
  theme: {
    colors: {
      deepnavy: "#1e1e2e",
      page: "#f5f5f5",
      surface: "#ffffff",
      subtle: "#f0f0f0",
      border: "#e5e7eb",
      "text-muted": "#6b7280",
    },
  },
});
